### ISSUE TITLE
why not releasing it as a gem on rubygems.org

### ISSUE THREAD

**Issue by rainchen** [fkchang/opal-irb#11]
Found this is useful but it's a pity that it's not a released gem

**Comment by fkchang** [comment]
I'd been thinking about releasing it as a gem, but I wanted to clean up some things, also I wanted to have some sort of mapping to which versions of Opal it will run against.  Originally, I've had to make some big changes w/version changes, but the latest works on 0.8 w/o any code changes, so maybe I can release it, though I'm working on better code completion in the multi line editor

**Comment by rainchen** [comment]
I tried it with opal 0.8.0, I think it's good enough to release. You can bump version any time when you think it's ready for next release. What a pity that when searching gems related to `opal`, this one is not on the result list: https://rubygems.org/search?utf8=%E2%9C%93&query=opal

**Comment by fkchang** [comment]
I just released 0.7.0 to match with 0.7.* opal, will be releasing one for 0.8.0 shortly.  Closing this issue
